stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t gleidsonlm/gitlab-ci-android:${CI_COMMIT_SHORT_SHA} .

push_latest:
  stage: push
  only:
    - master
  script:
    - docker tag gleidsonlm/gitlab-ci-android:${CI_COMMIT_SHORT_SHA} gleidsonlm/gitlab-ci-android:latest
    - docker push gleidsonlm/gitlab-ci-android:latest

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker tag gleidsonlm/gitlab-ci-android:${CI_COMMIT_SHORT_SHA} gleidsonlm/gitlab-ci-android:${CI_COMMIT_TAG}
    - docker push gleidsonlm/gitlab-ci-android:${CI_COMMIT_TAG}
